version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: code-review-app
    env_file:
      - .env
    environment:
      - REDIS_BROKER_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis